language: node_js
node_js:
  - '8'

sudo: false

cache:
  directories:
    - node_modules

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - mkdir -p dist/angular-resource-router
  - cp src/lib/package.json dist/angular-resource-router/
  - npm link dist/angular-resource-router
  - npm link angular-resource-router
  - npm run package
  - npm run buildapp

before_cache:
  - npm unlink angular-resource-router
