language: node_js
node_js:
  - '8'

sudo: required

cache:
  directories:
    - node_modules

before_script:
  - export CHROME_BIN=chromium-browser

script:
  - npm run bootstrap
  - npm run build
  - npm run buildapp

before_cache:
  - npm unlink angular-resource-router
