language: node_js
node_js:
  - '8'

sudo: false

cache:
  directories:
    - node_modules

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run bootstrap
  - npm run build
  - npm run buildapp

before_cache:
  - npm unlink angular-resource-router
